backend = "glx";
inactive-dim = 0.075;
inactive-dim-fixed = true;
xinerama-shadow-crop = true;
blur-background = false;
blur-kern = "3x3box"
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'slop'",
    "_GTK_FRAME_EXTENTS@:c"
];

shadow = true;
no-dock-shadow = true;
# shadow-offset-y = 0;
shadow-exclude-reg = "x25+0+0";
shadow-exclude = [
    "name *?= 'Mathematica'",
    "name *?= 'newtifyd'"
];
clear-shadow = true;

mark-ovredir-focused = true;

# Fading
fading = true;

# Fix fullscreen video freeze bug
vsync = "opengl-swc";
unredir-if-possible = true;


# vim: ft=conf
