#!/usr/bin/env fish

curl ^/dev/null http://www.prevision-meteo.ch/services/json/lys-lez-lannoy \
    | jq '(.current_condition.tmp|tostring) + "°C, " + .current_condition.condition' -M \
    | string trim -c '"'
